### ISSUE TITLE
Zadanie Google

### ISSUE THREAD

**Issue by robertostoja-lniski** [doqq123/kurs-programowania#9]
Mamy liste par [(4, 5), (5,8), (1,3)] i chcemy wygenerowac wszystkie mozliwe napisy powstałe z konkatenacji liczb z tych przedziałów. Z każdego przedziału musimy wybrać po jednej liczbie.

**Comment by doqq123** [comment]
4, 5
5, 6, 7, 8
1, 2, 3

**Comment by robertostoja-lniski** [comment]
1: 451
2: 452
3: 453
4: 461

n - 1: 582
n: 583

**Comment by robertostoja-lniski** [comment]
def v1(a, id):
    
    if id >= len(a):
        return

    poczatek_przedzialu_0, koniec_przedzialu_0 = a[id]
    for i in range(poczatek_przedzialu_0, koniec_przedzialu_0 + 1):
        print(f'{id} : {i}')
        v1(a, id + 1)
